#ifndef ShaderVariablesClouds_CS_HLSL2
#define ShaderVariablesClouds_CS_HLSL2
CBUFFER_START (ShaderVariablesClouds2)
float _EarthRadius;
float _LowestCloudAltitude;
float _HighestCloudAltitude;
float _MaxRayMarchingDistance;
float _NumPrimarySteps;
float _PhaseForward;
float _PhaseBackward;
float4 _ColA;
float4 _ColB;
float4 _WeatherTiling;
float _ColAMutiplier;
float _ColBMutiplier;
float _NumLightSteps;
float _DarknessThreshold;
float _LightAbsorptionThroughCloud;
float _LightAbsorptionTowardSun;
float2 _WindDirection;
float2 _WindVector;
float _VerticalShapeWindDisplacement;
float _VerticalErosionWindDisplacement;
float _DensityMultiplier;
float _WindSpeed;
float _BasicNoiseWindSpeed;
float _DetailNoiseWindSpeed;
float _WeatherWindSpeed;
float _BasicNoiseScale;
float _DetailNoiseScale;
float _AltitudeDistortion;
float _Coverage;
float _WeatherUVScale;
float _CloudCoverageUVScale;
float2 _blueNoiseScale;
CBUFFER_END
#endif
